# -*- coding: utf-8 -*-
"""Task-4) PDF_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8-l8pqGoQ8mKasKeTfyG3Dp7c3K712s
"""

import PyPDF2
from pdf2image import convert_from_path

pip install poppler-utils

# PDF to Text Conversion Function
def pdf_to_text(pdf_path, output_path):
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfFileReader(file)
        text = ''
        for page_num in range(reader.numPages):
            page = reader.getPage(page_num)
            text += page.extractText()

    with open(output_path, 'w') as file:
        file.write(text)

# PDF to Image Conversion Function
def pdf_to_images(pdf_path, output_path):
    images = convert_from_path(pdf_path)
    for i, image in enumerate(images):
        image.save(f"{output_path}/page_{i+1}.jpg", "JPEG")

# Main Conversion Function
def convert_pdf(pdf_path, output_path, format='text'):
    if format == 'text':
        pdf_to_text(pdf_path, output_path)
    elif format == 'images':
        pdf_to_images(pdf_path, output_path)
    else:
        raise ValueError("Invalid output format.")

# Entry point (CLI)
if __name__ == "__main__":
    pdf_path = input("Enter the path to the PDF file: ")
    output_path = input("Enter the output directory path: ")
    output_format = input("Enter the output format (text or images): ")

    convert_pdf(pdf_path, output_path, format=output_format.lower())
    print("Conversion completed.")