# -*- coding: utf-8 -*-
"""Task-2) To-Do_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8-l8pqGoQ8mKasKeTfyG3Dp7c3K712s
"""

tasks = []

def add_task(task):
    tasks.append(task)
    print("Task added successfully.")

def delete_task(task):
    if task in tasks:
        tasks.remove(task)
        print("Task deleted successfully.")
    else:
        print("Task not found.")

def mark_completed(task):
    if task in tasks:
        tasks.remove(task)
        print("Task marked as completed.")
    else:
        print("Task not found.")

def show_tasks():
    if tasks:
        print("Tasks:")
        for i, task in enumerate(tasks, 1):
            print(f"{i}. {task}")
    else:
        print("No tasks available.")

def to_do_list():
    while True:
        print("\nTodo List Menu:")
        print("1. Add Task")
        print("2. Delete Task")
        print("3. Mark Task as Completed")
        print("4. Show Tasks")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            task = input("Enter task: ")
            add_task(task)
        elif choice == '2':
            task = input("Enter task to delete: ")
            delete_task(task)
        elif choice == '3':
            task = input("Enter task to mark as completed: ")
            mark_completed(task)
        elif choice == '4':
            show_tasks()
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")

to_do_list()