# -*- coding: utf-8 -*-
"""Task-1) Image_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8-l8pqGoQ8mKasKeTfyG3Dp7c3K712s
"""

from PIL import Image
import os

def convert_image(input_image, output_format):
    try:
        # Open the image file
        with Image.open(input_image) as img:
            # Convert to desired format
            img = img.convert('RGB')
            # Save the converted image
            img.save(f'output.{output_format}', format=output_format.upper())
            print("Image converted successfully.")
    except Exception as e:
        print(f"Error: {e}")

def main():
    input_image = input("Enter the input image path: ")
    if not os.path.isfile(input_image):
        print("Error: Input image not found.")
        return

    output_format = input("Enter the desired output format (JPEG, PNG, BMP, GIF): ").upper()

    if output_format not in ['JPEG', 'PNG', 'BMP', 'GIF']:
        print("Error: Invalid output format.")
        return

    convert_image(input_image, output_format)

if __name__ == "__main__":
    main()