# -*- coding: utf-8 -*-
"""Task-2) Data_Analysis_with_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8-l8pqGoQ8mKasKeTfyG3Dp7c3K712s
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Loading Iris dataset from Seaborn
iris = sns.load_dataset('iris')

# Exploratory Data Analysis (EDA)
print("Data Sample:")
print(iris.head())

print("\nSummary Statistics:")
print(iris.describe())

print("\nData Types:")
print(iris.dtypes)

print("\nMissing Values:")
print(iris.isnull().sum())

# Performing data cleaning (remove outliers in 'petal_length')
Q1 = iris['petal_length'].quantile(0.25)
Q3 = iris['petal_length'].quantile(0.75)
IQR = Q3 - Q1   # Interquartile Range (IQR) method
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

cleaned_iris = iris[(iris['petal_length'] >= lower_bound) & (iris['petal_length'] <= upper_bound)]
print(Q1)
print(Q3)
print(lower_bound)
print(upper_bound)

# Aggregation
species_counts = iris['species'].value_counts()
print("\nSpecies Counts:")
print(species_counts)

# Visualizations
# 1.Pairplot
sns.pairplot(iris, hue='species')
plt.title('Pairplot of Iris Dataset')
plt.show()

# 2.Boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(x='species', y='petal_length', data=iris)
plt.title('Boxplot of Petal Length by Species')
plt.show()

# One-hot encode the 'species' column
iris_encoded = pd.get_dummies(iris, columns=['species'], drop_first=True)

# Correlation Calculations
correlation_matrix = iris_encoded.corr()

print("\nCorrelation Matrix:")
print(correlation_matrix)

# Heatmap of Correlation Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Heatmap of Correlation Matrix (Cleaned)')
plt.show()